config/routes.rb
Rails.application.routes.draw do
  resources :sdev153s
  resources :sdev140s
  resources :sdev120s
  resources :homes
  resources :abouts
  root 'homes#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active"><%= link_to "Home", homes_path, class:"nav-item nav-link"  %></a>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              SDEV120
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#"><%= link_to "Individual Final", sdev120s_path, class:"nav-item nav-link text-secondary"  %></a>
              <a class="dropdown-item" href="#"><%= link_to "Group Final", sdev120s_path, class:"nav-item nav-link text-secondary"  %></a>
            </div>
          </div>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              SDEV140
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#"><%= link_to "Python Scripts", sdev140s_path, class:"nav-item nav-link text-secondary"  %></a>
              <a class="dropdown-item" href="#"><%= link_to "Individual Final", sdev140s_path, class:"nav-item nav-link text-secondary"  %></a>
            </div>
          </div>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              SDEV153
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Individual Final</a>
              <a class="dropdown-item" href="#">Group Final</a>
            </div>
          </div>
          <a class="nav-item nav-link"><%= link_to 'About', abouts_path, class:"nav-item nav-link" %></a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>